version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    image: ghcr.io/chamburr/modmail-web:latest
    restart: unless-stopped
    ports:
      - '8000:6000'
    environment:
      - BASE_URI=${BASE_URI}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=6000
      - API_HOST=api
      - API_PORT=6001
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    image: ghcr.io/chamburr/modmail-api:latest
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_CLIENT_ID=${BOT_CLIENT_ID}
      - BOT_CLIENT_SECRET=${BOT_CLIENT_SECRET}
      - MAIN_SERVER=0
      - PREMIUM1_ROLE=0
      - PREMIUM3_ROLE=0
      - PREMIUM5_ROLE=0
      - PAYMENT_CHANNEL=0
      - PATRON_CHANNEL=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - BASE_URI=${BASE_URI}
      - API_HOST=0.0.0.0
      - API_PORT=6001
      - API_WORKERS=1
      - API_SECRET=supersecret
      - BOT_API_HOST=bot
      - BOT_API_PORT=6002
    depends_on:
      - redis

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=modmail
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres: