version: "3"

networks:
  backend:
    driver: bridge
    name: backend
  modmail_backend:
    name: modmail_backend
    external: true

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - modmail_backend
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - modmail_backend
    restart: unless-stopped

  logviewer:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    image: chamburr/modmail-web:latest
    container_name: logviewer
    networks:
      - modmail_backend
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:6000
    environment:
      - BASE_URI=${BASE_URI}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=${HTTP_PORT}
      - API_HOST=logviewer
      - API_PORT=6001
    depends_on:
      - api
  
  logfetcher:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    image: chamburr/modmail-api:latest
    container_name: logfetcher
    networks:
      - modmail_backend
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_CLIENT_ID=${BOT_CLIENT_ID}
      - BOT_CLIENT_SECRET=${BOT_CLIENT_SECRET}
      - MAIN_SERVER=0
      - PREMIUM1_ROLE=0
      - PREMIUM3_ROLE=0
      - PREMIUM5_ROLE=0
      - PAYMENT_CHANNEL=0
      - PATRON_CHANNEL=0
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=
      - BASE_URI=${BASE_URI}
      - API_HOST=0.0.0.0
      - API_PORT=6001
      - API_WORKERS=1
      - API_SECRET=${API_SECRET}
    depends_on:
      - redis

volumes:
    postgres:
    pgadmin:
  
# rabbitmqctl add_vhost qa1
