version: '3'

networks:
  modmail_backend:
    name: modmail_backend
    external: true

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_DB=modmail
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - modmail_backend
    ports:
      - 5433:6000

#  redis:
#    image: redis:7-alpine
#    restart: unless-stopped
#    container_name: redis
#    command:
#      sh -c "redis-server -p 6379 & redis-server -p 6378 & redis-server -p 6377"
#    networks:
#      - modmail_backend
 
volumes:
  postgres:
# rabbitmqctl add_vhost qa1
