version: "3"
#name: "${BOT_NAME}-stack"

networks:
  postgres:
    name: postgres
    external: true
  private:
    driver: bridge
    name: private-${BOT_NAME}

volumes:
  rabbitmq:
    name: rabbitmq-${BOT_NAME}
  redis:
    name: redis-${BOT_NAME}

services:
  bot:
    build:
      context: ..
      dockerfile: docker/bot/Dockerfile
    image: chamburr/modmail-bot:latest
    container_name: bot-${BOT_NAME}
    networks:
      - postgres
      - private
    restart: unless-stopped
    #volumes:
    #  - /home/plugins:/plugins
    env_file: frontend.env
    environment:
      - ENVIRONMENT=development
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_CLIENT_ID=${BOT_CLIENT_ID}
      - BOT_CLIENT_SECRET=${BOT_CLIENT_SECRET}
      - DEFAULT_PREFIX=${DEFAULT_PREFIX:-=}
      - DEFAULT_SERVER=${DEFAULT_SERVER}
      - BOT_CLUSTERS=1
      - MAIN_SERVER=
      - OWNER_USERS=${OWNER_USERS}
      - ADMIN_USERS=${ADMIN_USERS}
      - PREMIUM1_ROLE=0
      - PREMIUM3_ROLE=0
      - PREMIUM5_ROLE=0
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-modmail}
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - BASE_URI=${BASE_URI}
      - BOT_API_HOST=0.0.0.0
      - BOT_API_PORT=6002
      - TOPGG_TOKEN=
      - DBOTS_TOKEN=
      - DBL_TOKEN=
      - BOD_TOKEN=
    depends_on:
      - dispatch
      #      - postgres
      - redis
      - rabbitmq

  dispatch:
    image: chamburr/twilight-dispatch:latest
    container_name: dispatch-${BOT_NAME}
    networks:
      - private
    restart: unless-stopped
    env_file: frontend.env
    environment:
      - RUST_LOG=info
      - BOT_TOKEN=${BOT_TOKEN}
      - SHARDS_START=0
      - SHARDS_END=1
      - SHARDS_TOTAL=1
      - SHARDS_CONCURRENCY=1
      - SHARDS_WAIT=5
      - CLUSTERS=1
      - DEFAULT_QUEUE=true
      - RESUME=true
      - INTENTS=46593
      - LARGE_THRESHOLD=50
      - STATUS=${STATUS:-online}
      - ACTIVITY_TYPE=${ACTIVITY_TYPE-:0}
      - ACTIVITY_NAME=${ACTIVITY_NAME:-DM to Contact Staff}
      - LOG_CHANNEL=${LOG_CHANNEL:-0}
      - LOG_GUILD_CHANNEL=${LOG_GUILD_CHANNEL:-0}
      - STATE_ENABLED=true
      - STATE_MEMBER=false
      - STATE_MEMBER_TTL=60000
      - STATE_MESSAGE=false
      - STATE_MESSAGE_TTL=60000
      - STATE_PRESENCE=false
      - STATE_EMOJI=false
      - STATE_VOICE=false
      - STATE_OLD=false
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - PROMETHEUS_HOST=0.0.0.0
      - PROMETHEUS_PORT=8005
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq-${BOT_NAME}
    env_file: frontend.env
    networks:
      - private
    restart: unless-stopped
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file: frontend.env
    volumes:
      - redis:/data
    container_name: redis-${BOT_NAME}
    #    command:
    #      sh -c "redis-server -p 6379 & redis-server -p 6378 & redis-server -p 6377"
    networks:
      - private
